using System;
using System.Collections.Generic;
using System.Linq;

namespace Casper {
    /// <summary>
    /// This specification defines the values for the KeyboardEvent.code attribute,
    /// which is defined as part of the UI Events Specification [UIEvents].
    /// The code value contains information about the key event that can use used
    /// identify the 'PHYSICAL' key being pressed by the user.
    /// https://www.w3.org/TR/uievents-code/
    /// </summary>
    public enum KeyCode {

        // https://www.w3.org/TR/uievents-code/#key-alphanumeric-writing-system
        Backquote,
        Backslash,
        Backspace,
        BracketLeft,
        BracketRight,
        Comma,
        Digit0,
        Digit1,
        Digit2,
        Digit3,
        Digit4,
        Digit5,
        Digit6,
        Digit7,
        Digit8,
        Digit9,
        Equal,
        IntlBackslash,
        IntlRo,
        IntlYen,
        KeyA,
        KeyB,
        KeyC,
        KeyD,
        KeyE,
        KeyF,
        KeyG,
        KeyH,
        KeyI,
        KeyJ,
        KeyK,
        KeyL,
        KeyM,
        KeyN,
        KeyO,
        KeyP,
        KeyQ,
        KeyR,
        KeyS,
        KeyT,
        KeyU,
        KeyV,
        KeyW,
        KeyX,
        KeyY,
        KeyZ,
        Minus,
        Period,
        Quote,
        Semicolon,
        Slash,

        // https://www.w3.org/TR/uievents-code/#key-alphanumeric-functional
        AltLeft,
        AltRight,
        CapsLock,
        ContextMenu,
        ControlLeft,
        ControlRight,
        Enter,
        MetaLeft,
        MetaRight,
        ShiftLeft,
        ShiftRight,
        Space,
        Tab,

        // https://www.w3.org/TR/uievents-code/#key-controlpad-section
        Delete,
        End,
        Help,
        Home,
        Insert,
        PageDown,
        PageUp,

        // https://www.w3.org/TR/uievents-code/#key-arrowpad-section
        ArrowDown,
        ArrowLeft,
        ArrowRight,
        ArrowUp,

        // https://www.w3.org/TR/uievents-code/#key-numpad-section
        NumLock,
        Numpad0,
        Numpad1,
        Numpad2,
        Numpad3,
        Numpad4,
        Numpad5,
        Numpad6,
        Numpad7,
        Numpad8,
        Numpad9,
        NumpadAdd,
        NumpadBackspace,
        NumpadClear,
        NumpadClearEntry,
        NumpadComma,
        NumpadDecimal,
        NumpadDivide,
        NumpadEnter,
        NumpadEqual,
        NumpadHash,
        NumpadMemoryAdd,
        NumpadMemoryClear,
        NumpadMemoryRecall,
        NumpadMemoryStore,
        NumpadMemorySubtract,
        NumpadMultiply,
        NumpadParenLeft,
        NumpadParenRight,
        NumpadStar,
        NumpadSubtract,

        // https://www.w3.org/TR/uievents-code/#key-function-section
        Escape,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        Fn,
        FnLock,
        PrintScreen,
        ScrollLock,
        Pause,

        // https://www.w3.org/TR/uievents-code/#key-media
        BrowserBack,
        BrowserFavorites,
        BrowserForward,
        BrowserHome,
        BrowserRefresh,
        BrowserSearch,
        BrowserStop,
        Eject,
        LaunchApp1,
        LaunchApp2,
        LaunchMail,
        MediaPlayPause,
        MediaSelect,
        MediaStop,
        MediaTrackNext,
        MediaTrackPrevious,
        Power,
        Sleep,
        AudioVolumeDown,
        AudioVolumeMute,
        AudioVolumeUp,
        WakeUp,

        // https://www.w3.org/TR/uievents-code/#key-legacy
        Hyper,
        Super,
        Turbo,
        Abort,
        Resume,
        Suspend,
        Again,
        Copy,
        Cut,
        Find,
        Open,
        Paste,
        Props,
        Select,
        Undo,
        Hiragana,
        Katakana,
        Unidentified,
    }
}
